# Server configuration

current_server: gen3

servers:
  gen3:
    endpoint: "<https://gen3.endpoint>"
    profile: "<profile_name_from_init>"
    project_id: "<program-project>"
    bucket: "<bucket>"
  
  anvil:
    endpoint: "<https://anvil.endpoint>"
    terra_project: "<terra-project-id>"
