name: Install Script Test

on:
  release:
    types:
      published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  install:
    name: Test on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: linux, arch: amd64, runner: ubuntu-latest }
          - { os: linux, arch: arm64, runner: ubuntu-24.04-arm }
          - { os: darwin, arch: amd64, runner: macos-latest }
          - { os: darwin, arch: arm64, runner: macos-latest }

    steps:
      - name: Install Default Version (Latest Release)
        run: |
          TAG=${{ github.event.release.tag_name }}
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/calypr/git-drs/refs/tags/$TAG/install.sh)"
          source $HOME/.bashrc
          which git-drs
          git-drs --help
