name: Install Script Test

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  install:
    name: Test on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: linux, arch: amd64, runner: ubuntu-latest }
          # - { os: linux, arch: arm64, runner: ubuntu-latest-arm64 }
          # - { os: darwin, arch: amd64, runner: macos-latest }
          # - { os: darwin, arch: arm64, runner: macos-latest }

    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Install Default Version (Latest Release)
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/calypr/git-drs/refs/heads/main/install.sh)"  
          source $HOME/.bashrc
          which git-drs
          git-drs --help

      - name: Install Specific Version (Tag)
        run: |
          TAG=$(gh release view --json tagName --jq '.tagName' || echo "")
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/calypr/git-drs/refs/heads/main/install.sh)" -- $TAG
          source $HOME/.bashrc
          which git-drs
          git-drs --help
